version: '3'
services: # 集合                                
  jenkins:
    build: .
    # user: root 
    privileged: true
    restart: always # 重启方式
    image: iasuma/jenkins # 指定服务所使用的镜像 在这里我选择了 LTS (长期支持)
    container_name: jenkins # 容器名称
    ports: # 对外暴露的端口定义
      - 8088:8080 # 访问Jenkins服务端口
      - 50000:50000
    environment:
      TZ: Asia/Shanghai
    volumes: # 卷挂载路径
      - ./data:/var/jenkins_home